# -*- coding: utf-8 -*-
"""Copy of Data_Cleaning_Exercise_Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfsN6kPKn67isS3PZp6Ho-GN073NBMzs

# Data Cleaning in Python — Exercise

**Course:** Intro to Data Mining  
**Dataset:** Heart Failure Prediction dataset (loaded from a public URL — no file downloads needed!)  

---

# YOUR TURN: Practice Exercise

Now apply the same data cleaning pipeline from the Titanic exercise to a **new dataset**: the **Heart Failure Prediction** dataset.

This dataset combines 5 heart disease databases (918 patients total) and contains medical information about patients and whether or not they have heart disease. It has **text columns that need encoding**, potential outliers, and some tricky data quality issues — perfect for practicing everything we just learned.

**Your tasks** (follow the same steps from above):

1. Load the data and take a first look
2. Understand the data types and structure
3. Get descriptive statistics
4. Check for duplicates
5. Handle missing values (decide: drop column, drop row, or impute?)
6. Encode any categorical (`object`) columns
7. Detect and handle outliers
8. Scale the numerical features

The starter code below loads the dataset for you. The rest is up to you!

> **Hints:** Pay close attention to `.describe()` — not all missing values show up as NaN! Also, this dataset was made by combining multiple hospital databases, so check for duplicates.

### About the Heart Failure Prediction Dataset

| Column | Description | Type |
|--------|-------------|------|
| Age | Age in years | Numerical |
| Sex | M = Male, F = Female | Categorical |
| ChestPainType | TA = Typical Angina, ATA = Atypical Angina, NAP = Non-Anginal Pain, ASY = Asymptomatic | Categorical |
| RestingBP | Resting blood pressure (mm Hg) | Numerical |
| Cholesterol | Serum cholesterol (mg/dl) | Numerical |
| FastingBS | Fasting blood sugar > 120 mg/dl (1 = true, 0 = false) | Numerical |
| RestingECG | Normal, ST = ST-T wave abnormality, LVH = left ventricular hypertrophy | Categorical |
| MaxHR | Maximum heart rate achieved | Numerical |
| ExerciseAngina | Y = Yes, N = No | Categorical |
| Oldpeak | ST depression induced by exercise | Numerical |
| ST_Slope | Up = upsloping, Flat = flat, Down = downsloping | Categorical |
| HeartDisease | 1 = heart disease, 0 = no heart disease (TARGET) | Numerical |

### Step 1: Load the data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# The Heart Failure Prediction dataset — loaded from a public GitHub URL
# (Originally from Kaggle, combining 5 UCI heart disease databases)
url = 'https://raw.githubusercontent.com/xpy-10/DataSet/main/heart.csv'

heart = pd.read_csv(url)

print(f'Dataset shape: {heart.shape[0]} rows x {heart.shape[1]} columns')
heart.head()

"""### Step 2: Check data types and structure

Use `.info()` to see the data types and count non-null values.
"""

# YOUR CODE HERE
# Hint: heart.info()

heart.info()

"""### Step 3: Descriptive statistics

Use `.describe()`. Look for anything surprising in the min, max, or mean values.
"""

# YOUR CODE HERE
# Hint: heart.describe()
heart.describe()

"""### Step 4: Check for duplicates

How many duplicate rows are there? If any, remove them.
"""

# YOUR CODE HERE
# Hint: heart.duplicated().sum()
# To remove: heart = heart.drop_duplicates()

heart.duplicated().sum()
heart = heart.drop_duplicates()

"""### Step 5: Handle missing values

Check the percentage of missing values per column. Then decide what to do:
- Drop columns that are mostly missing
- Drop rows if very few are missing
- Impute (fill) with mean or median if a moderate amount is missing
"""

# YOUR CODE HERE
# Step 1: Find missing value percentages
# Hint: (heart.isnull().sum() / len(heart)) * 100

(heart.isnull().sum() / len(heart)) * 100

# Step 2: Decide and apply your strategy for each column with missing values

"""### Step 6: Encode categorical variables

Check if any columns are `object` type. If so, decide whether to use label encoding or one-hot encoding.

Hint: Look at `.info()` output — how many unique values does each `object` column have?
"""

# YOUR CODE HERE
# Hint: Check for object columns with:
# heart.select_dtypes(include='object').columns

heart.select_dtypes(include='object').columns
#
# For 2 categories: heart['col'] = heart['col'].map({'val1': 0, 'val2': 1})

heart['RestingECG'] = heart['RestingECG'].map({'val1': 0, 'val2': 1})

# For 3+ categories: heart = pd.get_dummies(heart, columns=['col'], drop_first=True)

heart = pd.get_dummies(heart, columns=['ChestPainType'], drop_first=True)

#
# Think about which columns have 2 categories vs. 3+ categories

print(heart.head())

"""### Step 7: Detect and handle outliers

Pick 2-3 numerical columns (e.g., `trestbps`, `chol`, `thalach`). Create box plots and use the IQR method.

Remember: think about whether outliers are real data or errors before removing them!
"""

# YOUR CODE HERE
# Hint: You can reuse the detect_outliers_iqr function from above
# Then create box plots with plt.boxplot()

"""### Step 8: Scale the numerical features

Apply Min-Max scaling to the numerical columns (not the target column).
"""

# YOUR CODE HERE
# Hint: Follow the same pattern from Section 8 of the tutorial

"""### Reflection Questions

After completing the exercise, answer these questions (add a text cell or answer here):

1. How did the Heart Disease dataset compare to the Titanic dataset in terms of data quality? Heart Disease dataset had more data points and more infomation.
2. Which missing value strategy did you use, and why?
3. Did you find any outliers? Did you remove them? Why or why not? I did not find any outliers.
4. If you were building a model to predict heart disease, which columns do you think would be most important? Age is the most important because you can determine when it starts to happen or try to predict symptoms early on.

---
*Great work! You now have hands-on experience with a complete data cleaning pipeline.* Dr. Thompson
"""